# Generated by Django 4.2.11 on 2024-05-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
